### PR TITLE
refs #3 - Added Chromium to Karma test matrix for CI.

### PR DESCRIPTION
**Pull request by n1k0**
Let's see if our friend Travis is happy.

### CODE REVIEW

**Comment by Natim** [comment]
```
Can not load "Chrome_travis_ci"!

Error: No provider for "launcher:Chrome". Can not use provider from the parent!
```

**Comment by n1k0** [comment]
I know, I miss a karma package for chrome support. Will add.

**Comment by n1k0** [comment]
BAM, it works.

**Comment by Natim** [comment]
:) Awesome

**Pull request merged**
