### PR TITLE
Refs #5 - Added code coverage reporting.

### PR DESCRIPTION
**Pull request by n1k0**
This patch adds support for generating code coverage reports, for CLI and html.

screen shot 2015-01-27 at 20 08 53
screen shot 2015-01-27 at 19 59 38

### CODE REVIEW

**Comment by n1k0** [comment]
Requesting review from either @natim, @ametaireau, @leplatrem, @tarekziade.

**Comment by leplatrem** [comment]
:clap: :) 

While trying to find some nitpick, I found out you could get rid of the coverage summary file since it's not used directly :) Although it might become handful on big projects #dunno

Could this work with coveralls ? (coverage badges are cool :))

**Comment by n1k0** [comment]
> While trying to find some nitpick, I found out you could get rid of the coverage summary file since it's not used directly :) Although it might become handful on big projects #dunno

Yep, I eventually used the complete one, but it's nice to have the simple one at hand, just in case. It's not that much dead code :)

> Could this work with coveralls ? (coverage badges are cool :))

I'll check that, thanks for the hint :)

**Comment by n1k0** [comment]
I'll check the coveralls integration in some other PR.

**Pull request merged**
