### PR TITLE
First draft of rest API client.

### PR DESCRIPTION
**Pull request by n1k0**
This is work in progress, introducing the js client for the Readinglist HTTP API. It uses the [rest](https://github.com/cujojs/rest) library to consume it.

Note that this is only a draft, and it's only unit-tested for now; that means the API is mocked out of the current [spec proposal](https://github.com/mozilla-services/readinglist/wiki/API-Design-proposal), which may or may not 100% reflect the state of the current server implementation.

I'm wondering if I shouldn't rather start writing functional tests so I consume the actual service, so I can provide feedback from the real thing. Thoughts?

Edit: Note that I could also start using the API for the webapp along writing the unit tests. But I fear having to keep both in sync will be a pain. Really, the functional testing approach would ease and smooth things a lot here.

### CODE REVIEW

**Comment by Natim** [comment]
Well then we can see if the server follow the api and if the api documentation is up to date but I think functional tests will be closer to the reality.

If you can make sure your mock stay true to the server then I am in.

**Comment by n1k0** [comment]
> If you can make sure your mock stay true to the server then I am in.

That synchronization effort really feels like duplicating the wheel, if I may — and is error prone. Starting a real server instance and playing the tests against it would solve that problem.

**Comment by n1k0** [comment]
> Object.assign is not a function

Bah, I should stop using nightly browsers. Will fix. But JavaScript engines on stable browsers, you're retarded.

**Comment by n1k0** [comment]
Green build, but the Coveralls bot seems drunk tonight.

**Comment by leplatrem** [comment]
My two cents regarding mock vs. real server : 
- units tests will be more relevant and a lot easier to write with mocked responses, especially for corner cases like error responses
- a (simpler) functional test suite could be helpful if ran on a real server, but might be painful to write if the database is not reset between each test

In daybed.js we've used sinon's fake server, and we didn't feel like duplicating efforts :)
https://github.com/spiral-project/daybed.js/blob/master/test/test.hello.js#L16-L23

**Comment by Natim** [comment]
Also the server api shouldn't change that much

**Pull request merged**
